networks:
  headscale_proxy_example:
    external: false

volumes:
  headscale-whoami-state:

services:
  whoami:
    image: traefik/whoami
    networks:
     - headscale_proxy_example

  headscale-whoami-proxy:
    image: dieterkoch/headscale-caddy-cloudflare-proxy
    volumes:
      # Persist the tailscale state directory so login state etc. is retained between restarts.
      - headscale-whoami-state:/var/lib/tailscale
    environment:
      # Hostname you want this instance to have on your headscale network.
      - TS_HOSTNAME=headscale-example
      # Your tailnet name including the full top level domain(s).
      - TS_TAILNET=vpn.example.com
      # Target service and port.
      - CADDY_TARGET=whoami:80
      # Optional extra arguments to pass when starting tailscale. Use this to include your Headscale login URL.
      - TS_EXTRA_ARGS=--login-server https://headscale.example.com
      # Cloudflare API token that is able to modify DNS entries for your configured MagicDNS domain.
      - CLOUDFLARE_DNS_API_TOKEN=your_cloudflare_token_here
    restart: on-failure
    init: true
    networks:
     - headscale_proxy_example
